// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSs3o-hmVglaIdRlf9G1ai0qDWQF3ojQI',
    appId: '1:824361733311:web:5c5218bb60b3c1f8a08a0a',
    messagingSenderId: '824361733311',
    projectId: 'shelter-app-cf77a',
    authDomain: 'shelter-app-cf77a.firebaseapp.com',
    storageBucket: 'shelter-app-cf77a.firebasestorage.app',
    measurementId: 'G-7VF8NKTQ9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD56l8kAuT9wC92r0PrrQfhL7dI-lDcwcI',
    appId: '1:824361733311:android:554056a70fb33a43a08a0a',
    messagingSenderId: '824361733311',
    projectId: 'shelter-app-cf77a',
    storageBucket: 'shelter-app-cf77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBksE-cW-crGTnw3epZgT13wH-1mMoUyWc',
    appId: '1:824361733311:ios:b015c6fef2b75148a08a0a',
    messagingSenderId: '824361733311',
    projectId: 'shelter-app-cf77a',
    storageBucket: 'shelter-app-cf77a.firebasestorage.app',
    iosClientId: '824361733311-ic7hb3lth1jdv9cmvoj1of3acigs1lkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.shelterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBksE-cW-crGTnw3epZgT13wH-1mMoUyWc',
    appId: '1:824361733311:ios:b015c6fef2b75148a08a0a',
    messagingSenderId: '824361733311',
    projectId: 'shelter-app-cf77a',
    storageBucket: 'shelter-app-cf77a.firebasestorage.app',
    iosClientId: '824361733311-ic7hb3lth1jdv9cmvoj1of3acigs1lkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.shelterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSs3o-hmVglaIdRlf9G1ai0qDWQF3ojQI',
    appId: '1:824361733311:web:465cc32bddf1346fa08a0a',
    messagingSenderId: '824361733311',
    projectId: 'shelter-app-cf77a',
    authDomain: 'shelter-app-cf77a.firebaseapp.com',
    storageBucket: 'shelter-app-cf77a.firebasestorage.app',
    measurementId: 'G-ECS8YEWWMH',
  );
}
